### ISSUE TITLE
Azure DevOps and Team Foundation Server Builds Failing

### ISSUE THREAD

**Issue by Jemimahk** [marcells/node-build-monitor#167]
Hi,

I have followed all documentation but when it comes to execution I get the following error, how do I resolve this?

Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = unset (Default: 1)
node-build-monitor is starting...
{ url: '<my_url>',
  collection: '<collection>',
  project: '<project>',
  username: '<username>',
  pat: '<personalaccesstoken>',
  queryparams: '&branchName=refs/heads/master&definitions=4,5,6,7&maxBuildsPerDefinition=1',
  includeQueued: false,
  showBuildStep: false } '2.0'
2:27:48 PM | Check for builds...
/snapshot/node-build-monitor/app/services/Tfs.js:195
          transformData(err, body, callback);
          ^

ReferenceError: transformData is not defined
    at __dirname.VSTSRestBuilds.async.autoInject.get_builds.request.makeRequest (/snapshot/node-build-monitor/app/services/Tfs.js:195:11)
    at Request._callback (/snapshot/node-build-monitor/app/requests.js:52:13)
    at Request.init.self.callback (/snapshot/node-build-monitor/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.init (/snapshot/node-build-monitor/node_modules/request/request.js:274:17)
    at new Request (/snapshot/node-build-monitor/node_modules/request/request.js:128:8)
    at request (/snapshot/node-build-monitor/node_modules/request/index.js:53:10)
    at Object.makeRequest (/snapshot/node-build-monitor/app/requests.js:17:7)
    at get_builds (/snapshot/node-build-monitor/app/services/Tfs.js:194:17)

**Comment by marcells** [comment]
Hm, how does your config look like? In the debug output `collection`, `project`, `username`, `pat` ist empty. That could be the issue.
