### ISSUE TITLE
VSTS  support

### ISSUE THREAD

**Issue by rengago** [marcells/node-build-monitor#31]
Team,

Do we have support for VSTS or  does tfs 2015  applies to vsts too ?

{
  "name": "Tfs2015",
  "configuration": {
    "url": "http://tfs-server:8080/tfs/DefaultCollection/TeamProject",
    "username": "domain\\buildadmin",
    "password": "buildadmin_password"
  }
}

**Comment by marcells** [comment]
Hi,

please use the `Tfs` service (Visual Studio Online) for it.
https://github.com/marcells/node-build-monitor#visual-studio-online

Kind regards

**Comment by rengago** [comment]
Trying to install  using docker 

"name": "Tfs",
  "configuration": {
    "collection": "DefaultCollection",
    "accountname": "xxxx@mail.com",
    "username": "xxxx@mail.com",
    "password": "xxxxx"
}

VSTS url  https://xxxx.visualstudio.com

Error: The TFS Project Collection named DefaultCollection was not found.
    at /build-mon/app/services/Tfs.js:75:28
    at Request._callback (/build-mon/app/services/Tfs.js:23:21)
    at Request.self.callback (/build-mon/node_modules/request/request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/build-mon/node_modules/request/request.js:1036:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/build-mon/node_modules/request/request.js:963:12)
    at emitNone (events.js:91:20)

**Comment by rengago** [comment]
Please can you let me know if i am missing something or any of my configuration has issues.
