### ISSUE TITLE
Crash when Gitlab service can't determine commit

### ISSUE THREAD

**Issue by CodeFarmer** [marcells/node-build-monitor#65]
`C:\Users\UKJGL01\node-build-monitor\app\services\GitLab.js:101
            return job && job.commit.author_name;
                                    ^

TypeError: Cannot read property 'author_name' of undefined
    at getAuthor (C:\Users\UKJGL01\node-build-monitor\app\services\GitLab.js:101:37)
    at simplifyBuild (C:\Users\UKJGL01\node-build-monitor\app\services\GitLab.js:83:31)
    at C:\Users\UKJGL01\node-build-monitor\app\services\GitLab.js:58:39
    at Request._callback (C:\Users\UKJGL01\node-build-monitor\app\services\GitLab.js:36:17)
    at Request.self.callback (C:\Users\UKJGL01\node-build-monitor\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\UKJGL01\node-build-monitor\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
`

**Comment by marcells** [comment]
Hm, strange. Did it work before? Were you able to resolve that issue or is it still active in the meantime? Maybe @arunkumarsundaramurthy has an idea. Recently he made some changes there.

**Comment by ntamas** [comment]
The pull request referenced above shows a workaround for this issue.
