### ISSUE TITLE
TFS 2017 Unexpected token

### ISSUE THREAD

**Issue by nitr8** [marcells/node-build-monitor#84]
Hiya I have been struggling with this for some time now. I have tried stand-alone and node both.

We using TFS 2017 latest patches = only non stock on setup was SSL and NTLM (TFSConfig Authentication /provider:NTLM /siteType:ApplicationTier)

```json
    {
      "name": "Tfs2015",
      "configuration": {
        "url": "https://de-tfs-01/tfs/source/products",
		"authentication": "ntlm",
		"username": "CORP\\a.myaccount",
		"password": "p5pqmydk6fhpas3j2gpylxowsvw7szic"
      }
    }
```

This is the output
```
node-build-monitor 0.9.27 is listening on port 3000...
undefined:1
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at C:\snapshot\node-build-monitor\app\requests.js:13:30
    at finalCallback (C:\snapshot\node-build-monitor\node_modules\httpreq\lib\httpreq.js:98:7)
    at IncomingMessage.<anonymous> (C:\snapshot\node-build-monitor\node_modules\httpreq\lib\httpreq.js:376:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

im also running non SSL on 8080 so tried that and also with / without NTLM also went back to lab box withs stock TFS 2017 that I did a clean install on - and no joys there too.

Anything i can do to troubleshoot?

**Comment by marcells** [comment]
Hm, okay. We use it with TFS 2017 and http/8080 without Ntlm.

It seems like the request returns an unexpected error page, instead of a json object.

Could you try to debug into the request and post the response here?

**Comment by nitr8** [comment]
Hi marecells,

Thanks for the feedback.

Its using the correct url (I added 80 / 443 in addition to 8080) 

http://de-tfs-01/tfs/Source/Products/_apis/build/Builds?$top=30 is what its calling and when i visit that url i get the json obect and its valid - see image bellow.

![out](https://user-images.githubusercontent.com/541890/32592471-264ef77a-c524-11e7-8009-0f6bb3b5a732.png)

Here is it with some debug into it:

```
C:\projects\node-build-monitor\app>node app.js
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = unset (Default: 1)
node-build-monitor is starting...
07:59:54 | Check for builds...
07:59:54 | http://de-tfs-01/tfs/Source/Products/_apis/build/Builds?$top=30
07:59:54 | { makeRequest: [Function: makeRequest] }
node-build-monitor 0.9.27 is listening on port 3000...
undefined:1
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\projects\node-build-monitor\app\requests.js:13:30
    at finalCallback (C:\projects\node-build-monitor\node_modules\httpreq\lib\httpreq.js:98:7)
    at IncomingMessage.<anonymous> (C:\projects\node-build-monitor\node_modules\httpreq\lib\httpreq.js:376:9)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by marcells** [comment]
That's really strange. Something has to be different. Maybe the authentication.

Can you output the whole ich content of the response body (starting with `<!DOCTYPE html PUBLIC`) of node-build-monitor?

**Comment by nitr8** [comment]
Hey marecells,

Thanks for all your help on this i really appreciate it :) so here is the response body from node-build-mon vs curl.

```
Printing environment Variables...
    PORT = unset (Default: 3000)
    NODE_TLS_REJECT_UNAUTHORIZED = 1
node-build-monitor is starting...
14:22:24 | Check for builds...
14:22:24 | http://de-tfs-01/tfs/Source/Products/_apis/build/Builds?$top=30
14:22:24 | { makeRequest: [Function: makeRequest] }
node-build-monitor 0.9.27 is listening on port 3000...
{ headers:
   { 'content-type': 'text/html',
     server: 'Microsoft-IIS/10.0',
     'x-tfs-processid': 'fb0b7387-ec50-42ee-942f-dc73ba497f9f',
     activityid: '9d071573-1c15-47a5-abeb-c1e930446985',
     'x-tfs-session': '9d071573-1c15-47a5-abeb-c1e930446985',
     'x-vss-e2eid': '9d071573-1c15-47a5-abeb-c1e930446985',
     'x-frame-options': 'SAMEORIGIN',
     'www-authenticate': 'Bearer, NTLM, Negotiate',
     'x-powered-by': 'ASP.NET',
     p3p: 'CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"',
     'lfs-authenticate': 'NTLM',
     'x-content-type-options': 'nosniff',
     date: 'Thu, 09 Nov 2017 13:22:24 GMT',
     connection: 'close',
     'content-length': '1293' },
  statusCode: 401,
  body: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Server Error</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>\r\n  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n',
  cookies: [] }
undefined:1
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\projects\node-build-monitor\app\requests.js:14:30
    at finalCallback (C:\projects\node-build-monitor\node_modules\httpreq\lib\httpreq.js:98:7)
    at IncomingMessage.<anonymous> (C:\projects\node-build-monitor\node_modules\httpreq\lib\httpreq.js:376:9)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

curl -v http://de-tfs-01/tfs/Source/Products/_apis/build/Builds?$top=30 --ntlm -u CORP\\a.myaccount
```
> GET /tfs/Source/Products/_apis/build/Builds?$top=30 HTTP/1.1
> Host: de-tfs-01
> Authorization: NTLM TlRMTVNTUAABAAAAB4IIogAAAAAAAAAAAAAAAAAAAAAKADk4AAAADw==
> User-Agent: curl/7.56.1
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Content-Type: text/html; charset=us-ascii
< Server: Microsoft-HTTPAPI/2.0
< WWW-Authenticate: NTLM TlRMTVNTUAACAAAACAAIADgAAAAFgomi5arB/o2Olr8AAAAAAAAAAI4AjgBAAAAACgA5OAAAAA9DAE8AUgBQAAIACABDAE8AUgBQAAEAEgBEAEUALQBUAEYAUwAtADAAMQAEABQAYwBvAHIAcAAuAGwAbwBjAGEAbAADACgARABFAC0AVABGAFMALQAwADEALgBjAG8AcgBwAC4AbABvAGMAYQBsAAUAFABjAG8AcgBwAC4AbABvAGMAYQBsAAcACADIt2oUZlnTAQAAAAA=
< Date: Thu, 09 Nov 2017 14:21:48 GMT
< Content-Length: 341
<
* Ignoring the response-body
* Connection #0 to host de-tfs-01 left intact
* Issue another request to this URL: 'http://de-tfs-01/tfs/Source/Products/_apis/build/Builds?$top=30'
* Found bundle for host de-tfs-01: 0xafe520 [can pipeline]
* Re-using existing connection! (#0) with host de-tfs-01
* Connected to de-tfs-01 (192.168.150.12) port 80 (#0)
* Server auth using NTLM with user 'CORP\wayne.humphrey'
> GET /tfs/Source/Products/_apis/build/Builds?$top=30 HTTP/1.1
> Host: de-tfs-01
> Authorization: NTLM TlRMTVNTUAADAAAAGAAYAJIAAAAWARYBqgAAAAgACABYAAAAHAAcAGAAAAAWABYAfAAAAAAAAADAAQAABYKIogoAOTgAAAAPJ7q5JqMhw9Qo8IMKCHvv5UMATwBSAFAAdwBhAHkAbgBlAC4AaAB1AG0AcABoAHIAZQB5AEQARQAtAFIAUwBIAC0AVwBBAEgAVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkbSaG0Yfn4ZYReVbYtaWkAQEAAAAAAADIt2oUZlnTAbc4BHAQSF1kAAAAAAIACABDAE8AUgBQAAEAEgBEAEUALQBUAEYAUwAtADAAMQAEABQAYwBvAHIAcAAuAGwAbwBjAGEAbAADACgARABFAC0AVABGAFMALQAwADEALgBjAG8AcgBwAC4AbABvAGMAYQBsAAUAFABjAG8AcgBwAC4AbABvAGMAYQBsAAcACADIt2oUZlnTAQYABAACAAAACAAwADAAAAAAAAAAAQAAAAAgAACuL/KKbNcZYdpHZwvPPo/IQ1AdIgOAUCTnpYSJSdD47woAEAAAAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAA==
> User-Agent: curl/7.56.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-cache
< Pragma: no-cache
< Content-Type: application/json; charset=utf-8; api-version=3.2
< Expires: -1
< Server: Microsoft-IIS/10.0
< X-TFS-ProcessId: fb0b7387-ec50-42ee-942f-dc73ba497f9f
< ActivityId: 9d072b99-1c15-47a5-abeb-c1e930446985
< X-TFS-Session: 9d072b99-1c15-47a5-abeb-c1e930446985
< X-VSS-E2EID: 9d072b99-1c15-47a5-abeb-c1e930446985
< X-FRAME-OPTIONS: SAMEORIGIN
< X-VSS-UserData: 5d4db890-7ff7-45e3-bd6f-520b522a8cbd:wayne.humphrey
< X-AspNet-Version: 4.0.30319
< Persistent-Auth: true
< X-Powered-By: ASP.NET
< P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
< Lfs-Authenticate: NTLM
< X-Content-Type-Options: nosniff
< Date: Thu, 09 Nov 2017 14:21:48 GMT
< Content-Length: 98882
<
{"count":30,"value":[{"_links":{"self":{"href":"http://de-tfs-01/tfs/Source/GUID/_apis/build/Builds/3077"},"web":{"ALLMYBUILDDATA":false},"keepForever":false,"retainedByRelease":false}]}* Connection #0 to host de-tfs-01 left intact
```

so i have no idea why curl gives me a 401 first but then a 200 with the relvant payload.

**Comment by marcells** [comment]
Hi, sure, I'll help you. We have to check what's going on there.

Are you sure, that you're using the correct password?

Could you compare the request headers for the node-build-monitor requests and the curl request with Fiddler? Could you use it without NTLM, too?
